# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20170223_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Recommends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='shopsproducts',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shopsproducts',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='shops',
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=600),
        ),
        migrations.DeleteModel(
            name='ShopsProducts',
        ),
        migrations.AddField(
            model_name='recommends',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Products'),
        ),
        migrations.AddField(
            model_name='recommends',
            name='recommend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Movies'),
        ),
    ]
