# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20170322_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommends',
            name='item',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='recommends',
            name='recommend',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
