# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_products_recommend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='recommend',
        ),
        migrations.AddField(
            model_name='recommends',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.Products', verbose_name='product'),
            preserve_default=False,
        ),
    ]
