# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20170322_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommends',
            name='product',
        ),
        migrations.AlterField(
            model_name='recommends',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Products'),
        ),
    ]
